[package]
name = "dtl-lexer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
rand = "0.8"
miette.workspace = true
thiserror.workspace = true
num-bigint.workspace = true
unicode-xid =  "0.2.6"
